services:
  - type: web
    name: excellm
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn frontend.app:app --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: RENDER
        value: "true"
