services:
  - type: web
    name: excellm
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: free
    resources:
      cpu: 2
      memory: 512MB
      disk: 10GB
